version: '3.9'
services:
  map:
    build: .
    ports:
      - '42011:80'
    # Optional: live tiles updates via bind mount
    volumes:
      - ./tiles:/usr/share/nginx/html/tiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
